<a href="https://colab.research.google.com/github/fereshtehdehkhoda/Example-15-Rotation-matrix/blob/main/Rotation_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#اگر بردار u = (2, 3)
#را 30 درجه پاد ساعتگرد دوران دهید، مختصات بردار دوران‌یافته کدام است؟

In [ ]:
import math
import numpy as np

In [ ]:
u=np.array([2,3])
u

array([2, 3])

In [ ]:
R=np.array([[(3**0.5)/2,-0.5],[0.5,(3**0.5)/2]])
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [ ]:
np.dot(R,u)

array([0.23205081, 3.59807621])